{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatcli.fullname" . }}
  labels:
    {{- include "chatcli.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.server.token }}
  CHATCLI_SERVER_TOKEN: {{ .Values.server.token | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.googleaiApiKey }}
  GOOGLEAI_API_KEY: {{ .Values.secrets.googleaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.xaiApiKey }}
  XAI_API_KEY: {{ .Values.secrets.xaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.stackspotClientId }}
  CLIENT_ID: {{ .Values.secrets.stackspotClientId | quote }}
  {{- end }}
  {{- if .Values.secrets.stackspotClientKey }}
  CLIENT_KEY: {{ .Values.secrets.stackspotClientKey | quote }}
  {{- end }}
  {{- if .Values.secrets.stackspotRealm }}
  STACKSPOT_REALM: {{ .Values.secrets.stackspotRealm | quote }}
  {{- end }}
  {{- if .Values.secrets.stackspotAgentId }}
  STACKSPOT_AGENT_ID: {{ .Values.secrets.stackspotAgentId | quote }}
  {{- end }}
{{- end }}
